### ISSUE TITLE
ruler isn't scaling correctly

### ISSUE THREAD

**Issue by rhbecker** [lkcampbell/brackets-ruler#41]
I've disabled all extensions except for brackets-ruler. I've reset the theme to the Brackets default. No matter what, the ruler isn't scaled correctly.

The guide displays in the proper place relative to my guidePosition setting, but relative to the ruler, it appears to be in the wrong place. For every 10 columns of actual real estate, the ruler thinks it's 9 columns. So, when I have guidePosition set to 80, the guide appears to be at 72, relative to the ruler.

I'm on ...
* Release 1.1 build 1.1.0-15558 (release ea908cae5)
* Windows 7
* brackets-themes.fontType: "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace"

![ruler](https://cloud.githubusercontent.com/assets/224732/5944884/4580ed9e-a6df-11e4-9735-9b328b889351.png)

**Comment by lkcampbell** [comment]
@rhbecker agreed, I have been seeing some scrolling problems recently. I will take a look into it, thanks.

**Comment by lkcampbell** [comment]
@rhbecker, sorry haven't looked at this in a while. Is this issue still a problem for you?

I'm having a difficult time reproducing the problem, probably because I am on a Mac instead of a Windows machine.

From your screenshot, it looks like the tick marks are failing to resize correctly. Can you check out a few things for me?

What size is your font?

Resize the font and see if the tick mark size corrects itself after you do that.

Go into `Debug > Show Developer Tools` and see if there are any errors.

**Comment by lkcampbell** [comment]
Also, if you happen to be using a development build of Brackets, I would be interested in seeing if you have any failures on the Unit Tests.

If `Debug > Run Tests` is available, would you mind jumping to the `Extensions` tab and clicking on the `Column Ruler` test suite and let me know if it reports any errors? Not including the Gutter Width error which is a known issue I am working to fix today.

If `Debug > Run Tests` is *not* available, you aren't on a Developer build, so don't worry about it.

**Comment by lkcampbell** [comment]
@rhbecker, actually, before you try any of that, update the Column Ruler extension to version 2.3.8. Changes I implemented for a couple of other bugs may fix this issue as well.

Let me know either way.

**Comment by lkcampbell** [comment]
@rhbecker, I'm closing as fixed. Reopen if I am incorrect in this assumption.

**Comment by rhbecker** [comment]
I've updated to 2.3.9 (appears to be the latest) and this issue persists.

I'm not on the developer version of Brackets.

I did try updating Brackets to the latest: Release 1.2 build 1.2.0-15697 (release 8f82e2a97). This update did not change my experience.

With only this ruler extension loaded, I don't get any errors (or even warnings) in the dev tools console.

According to the dev tools inspector, my font size is 12px. If I scale the font up by 3 (hitting Ctrl++ 3 times), the font size becomes 15px and the ruler appears to be properly scaled. When I restore to "normal" font size (Ctrl+0), I get what was in my prior screenshot.

**Comment by rhbecker** [comment]
Oh, and as far as I know, I'm not able to reopen an issue you've closed. I assume these replies are sufficient.

**Comment by lkcampbell** [comment]
@rhbecker, I am rewriting this entire extension and tossing on the ruler interface. It will run completely on preferences very soon. Maintaining it in the face of constant Brackets changes is not working. Stay tuned for version 3.0.
